[package]

name = "kaiseki"
version = "0.1.0"
authors = [ "William Yao <williamyaoh@gmail.com>" ]

[dependencies]

regex = "^0.2.0"
error-chain = "^0.9.0"
docopt = "^0.7.0"
rustc-serialize = "^0.3.0"
