[package]

name = "kaiseki"
version = "0.2.4"
authors = [ "William Yao <williamyaoh@gmail.com>" ]

[dependencies]

regex = "^0.2.0"
error-chain = "^0.9.0"
structopt = ">=0.0.3, <0.1.0"
structopt-derive = ">=0.0.3, <0.1.0"
